env:
  browser: true
  es2020: true
  node: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:import/typescript
  - plugin:cypress/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'global-require': 'off',
    'no-use-before-define': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/jsx-props-no-spreading': 'off',
    'import/prefer-default-export': 'off',
    'import/no-extraneous-dependencies': ['error', { 'devDependencies': true }],
    'react/jsx-filename-extension':
      [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
    'import/extensions':
      [
        'error',
        'ignorePackages',
        { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' },
      ],
  }
